// Refreshes the homepage YouTube ribbon from the channel's public Atom feed (no API key):
//   node scripts/fetch-youtube.mjs
// Writes content/youtube.ts (newest first) and saves each thumbnail under public/youtube/<id>.jpg,
// because the CSP allows same-origin images only and the site makes no third-party requests.
// The feed carries the channel's 15 most recent uploads; that is the ribbon's whole catalogue.
import { mkdir, writeFile, access } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";

const CHANNEL_ID = "UCdUFIRwrZMoq4oUvPt3KuPQ";
const FEED = `https://www.youtube.com/feeds/videos.xml?channel_id=${CHANNEL_ID}`;
const root = fileURLToPath(new URL("..", import.meta.url));
const thumbnailDir = path.join(root, "public", "youtube");
const contentFile = path.join(root, "content", "youtube.ts");

const decode = (text) =>
  text
    .replace(/&amp;/g, "&")
    .replace(/&lt;/g, "<")
    .replace(/&gt;/g, ">")
    .replace(/&quot;/g, '"')
    .replace(/&#39;/g, "'")
    .replace(/&apos;/g, "'");
const field = (entry, tag) => {
  const match = entry.match(new RegExp(`<${tag}>([^<]*)</${tag}>`));
  return match ? decode(match[1].trim()) : "";
};

const response = await fetch(FEED, { headers: { "user-agent": "in2itebs-site-build" } });
if (!response.ok) throw new Error(`feed ${response.status}`);
const xml = await response.text();
const entries = [...xml.matchAll(/<entry>([\s\S]*?)<\/entry>/g)].map(([, entry]) => ({
  id: field(entry, "yt:videoId"),
  title: field(entry, "title"),
  published: field(entry, "published").slice(0, 10),
}));
if (!entries.length) throw new Error("feed has no entries");
const videos = entries
  .filter((video) => /^[\w-]{11}$/.test(video.id) && video.title)
  .sort((a, b) => (a.published < b.published ? 1 : a.published > b.published ? -1 : 0));

await mkdir(thumbnailDir, { recursive: true });
for (const video of videos) {
  const file = path.join(thumbnailDir, `${video.id}.jpg`);
  try {
    await access(file);
    continue;
  } catch {
    // not saved yet
  }
  const image = await fetch(`https://i.ytimg.com/vi/${video.id}/hqdefault.jpg`);
  if (!image.ok) throw new Error(`thumbnail ${video.id} ${image.status}`);
  await writeFile(file, Buffer.from(await image.arrayBuffer()));
}

const lines = videos.map(
  (video) =>
    `  { id: ${JSON.stringify(video.id)}, title: ${JSON.stringify(video.title)}, published: ${JSON.stringify(video.published)} },`,
);
await writeFile(
  contentFile,
  `// Generated by scripts/fetch-youtube.mjs from the channel's public feed; do not edit by hand.
// Newest first. Thumbnails are saved under public/youtube/<id>.jpg by the same script.
export const YOUTUBE_CHANNEL_URL = "https://www.youtube.com/channel/${CHANNEL_ID}";
export type YoutubeVideo = { id: string; title: string; published: string };
export const youtubeVideos: YoutubeVideo[] = [
${lines.join("\n")}
];
`,
);
console.log(`wrote ${videos.length} videos to content/youtube.ts (newest ${videos[0].published})`);
