"use client";
import { useEffect, useRef, useState } from "react";
import { ArrowLeft, ArrowRight, ArrowUpRight, Play } from "lucide-react";
import { Container } from "@/components/ui/container";
import { YOUTUBE_CHANNEL_URL, youtubeVideos } from "@/content/youtube";

// UTC on purpose: the catalogue stores calendar dates, and a fixed zone keeps the server render and
// every visitor's browser agreeing on the day.
const dateFormat = new Intl.DateTimeFormat("en-GB", {
  day: "numeric",
  month: "short",
  year: "numeric",
  timeZone: "UTC",
});

/**
 * The channel's latest uploads as a horizontal scroll-snap carousel, newest first, right above the
 * footer (2026-09-15 17:08). Each card is a direct link to the video on YouTube; thumbnails are
 * self-hosted under public/youtube (the CSP allows same-origin images only), and the catalogue is
 * generated by scripts/fetch-youtube.mjs from the channel's public feed. The track scrolls natively
 * (touch, trackpad, keyboard); the two arrow buttons page it for mouse users and only render while
 * the track actually overflows.
 */
export function YoutubeRibbon() {
  const track = useRef<HTMLUListElement>(null);
  const [overflows, setOverflows] = useState(false);

  useEffect(() => {
    const element = track.current;
    if (!element) return;
    const measure = () => setOverflows(element.scrollWidth > element.clientWidth + 1);
    measure();
    const observer = new ResizeObserver(measure);
    observer.observe(element);
    return () => observer.disconnect();
  }, []);

  const page = (direction: -1 | 1) => {
    const element = track.current;
    if (!element) return;
    element.scrollBy({ left: direction * element.clientWidth * 0.8, behavior: "smooth" });
  };

  if (!youtubeVideos.length) return null;
  return (
    <section
      data-youtube-ribbon
      aria-labelledby="youtube-ribbon-title"
      className="border-t border-border-subtle bg-surface py-14 md:py-20"
    >
      <Container>
        <div className="mb-8 flex flex-wrap items-end justify-between gap-6">
          <div>
            <p className="text-sm font-semibold text-gold">From our channel</p>
            <h2 id="youtube-ribbon-title" className="mt-3 max-w-2xl text-h2 font-semibold">
              Latest videos from In2IT EBS.
            </h2>
            <p className="mt-4 max-w-2xl text-base leading-relaxed text-foreground-muted">
              Go-lives, customer testimonials and event highlights, newest first. Each card opens the video on YouTube.
            </p>
          </div>
          <div className="flex flex-wrap items-center gap-3">
            <a
              href={YOUTUBE_CHANNEL_URL}
              target="_blank"
              rel="noopener noreferrer"
              className="inline-flex min-h-11 items-center gap-3 text-sm font-semibold text-gold hover:underline"
            >
              Visit our YouTube channel <ArrowUpRight aria-hidden size={18} />
            </a>
            {overflows && (
              <span className="flex items-center gap-2">
                <button
                  type="button"
                  onClick={() => page(-1)}
                  aria-label="Show earlier videos"
                  className="glass-pill h-11 w-11 justify-center p-0 text-foreground hover:text-gold"
                >
                  <ArrowLeft size={18} aria-hidden />
                </button>
                <button
                  type="button"
                  onClick={() => page(1)}
                  aria-label="Show later videos"
                  className="glass-pill h-11 w-11 justify-center p-0 text-foreground hover:text-gold"
                >
                  <ArrowRight size={18} aria-hidden />
                </button>
              </span>
            )}
          </div>
        </div>
        <ul
          ref={track}
          data-youtube-track
          aria-label="Latest videos, newest first"
          className="video-ribbon-track -mx-5 flex snap-x snap-mandatory gap-4 overflow-x-auto scroll-pl-5 px-5 pb-4 md:-mx-8 md:scroll-pl-8 md:px-8"
        >
          {youtubeVideos.map((video, index) => (
            <li key={video.id} className="w-[min(82vw,20rem)] shrink-0 snap-start">
              <a
                href={`https://www.youtube.com/watch?v=${video.id}`}
                target="_blank"
                rel="noopener noreferrer"
                data-youtube-video={video.id}
                className="glass-card group block overflow-hidden rounded-surface"
              >
                <span className="relative block aspect-video bg-logo-surface">
                  {/* eslint-disable-next-line @next/next/no-img-element */}
                  <img
                    src={`/youtube/${video.id}.jpg`}
                    alt=""
                    width={480}
                    height={360}
                    loading={index < 3 ? "eager" : "lazy"}
                    className="h-full w-full object-cover transition-transform duration-300 group-hover:scale-[1.03]"
                  />
                  <span aria-hidden className="absolute inset-0 flex items-center justify-center">
                    <span className="glass-pill h-12 w-12 justify-center p-0 text-foreground">
                      <Play size={18} aria-hidden />
                    </span>
                  </span>
                </span>
                <span className="block p-4">
                  <span className="line-clamp-2 text-sm font-semibold text-foreground">{video.title}</span>
                  <span className="mt-2 block text-xs text-foreground-muted">
                    <time dateTime={video.published}>
                      {dateFormat.format(new Date(`${video.published}T00:00:00Z`))}
                    </time>
                    <span aria-hidden> · </span>
                    <span>Watch on YouTube</span>
                  </span>
                </span>
              </a>
            </li>
          ))}
        </ul>
      </Container>
    </section>
  );
}
