import type { Client } from "./types";

export const clients: Client[] = [
  { slug: "airports-authority-of-india", name: "Airports Authority of India", sectors: ["PSUs"], logo: "/logos/clients/airports-authority-of-india.png" },
  // Deck lists Mrs Bectors once, with its Cremica and English Oven brand marks beneath; the Cremica mark carries the
  // "Mrs Bector's" name, so it stands for the parent and the separate text-line entry was a duplicate in the ribbon.
  { slug: "mrs-bectors", name: "Mrs Bectors Food Specialities (Cremica)", sectors: ["Food & Beverages"], logo: "/logos/deck-clients/cremica.png" },
  { slug: "english-oven", name: "English Oven", sectors: ["Food & Beverages"], logo: "/logos/deck-clients/english-oven.png" },
  { slug: "ajinomoto", name: "Ajinomoto", sectors: ["Food & Beverages"], logo: "/logos/clients/ajinomoto.svg" },
  { slug: "bio-pharma-services", name: "Bio Pharma Services", sectors: ["Food & Beverages"], logo: "/logos/deck-clients/bio-pharma-services.png" },
  { slug: "waycool", name: "WayCool Foods", sectors: ["Food & Beverages"], logo: "/logos/deck-clients/p42-Image231.png" },
  { slug: "breadtalk", name: "BreadTalk", sectors: ["Food & Beverages"], logo: "/logos/clients/breadtalk.svg" },
  { slug: "vahdam", name: "Vahdam India", sectors: ["Food & Beverages"], logo: "/logos/clients/vahdam.png" },
  { slug: "avra", name: "Avra Laboratories", sectors: ["Health & Pharma"], logo: "/logos/deck-clients/p42-Image251.png" },
  { slug: "sentiss", name: "Sentiss Pharma", sectors: ["Health & Pharma"], logo: "/logos/deck-clients/p42-Image239.png" },
  { slug: "unichem", name: "Unichem Laboratories", sectors: ["Health & Pharma"], logo: "/logos/clients/unichem.svg" },
  { slug: "manipal-hospitals", name: "Manipal Hospitals", sectors: ["Health & Pharma"], logo: "/logos/clients/manipal-hospitals.png" },
  { slug: "centrient", name: "Centrient Pharmaceuticals", sectors: ["Health & Pharma"], logo: "/logos/deck-clients/p42-Image254.png" },
  { slug: "st-johns", name: "St John's National Academy of Health Sciences", sectors: ["Health & Pharma"], logo: "/logos/clients/st-johns.png" },
  { slug: "zcl-chemicals", name: "ZCL Chemicals", sectors: ["Health & Pharma"], logo: "/logos/deck-clients/p42-Image243.png" },
  { slug: "human-health", name: "Human Health", sectors: ["Health & Pharma"], logo: "/logos/deck-clients/p42-Image238.png" },
  { slug: "aknamed", name: "Aknamed", sectors: ["Health & Pharma"], logo: "/logos/deck-clients/p42-Image247.png" },
  { slug: "tata-md", name: "Tata MD", sectors: ["Health & Pharma"], logo: "/logos/clients/tata-md.png" },
  { slug: "natural-remedies", name: "Natural Remedies", sectors: ["Health & Pharma"], logo: "/logos/deck-clients/natural-remedies.png" },
  { slug: "bata", name: "Bata", sectors: ["Apparel & Fashion"], logo: "/logos/clients/bata.svg" },
  { slug: "rasasi", name: "Rasasi Perfumes", sectors: ["Apparel & Fashion"], logo: "/logos/deck-clients/p42-Image260.png" },
  { slug: "welspun-flooring", name: "Welspun Flooring", sectors: ["Apparel & Fashion"], logo: "/logos/deck-clients/p42-Image262.png" },
  { slug: "rp-apparels", name: "RP Apparels", sectors: ["Apparel & Fashion"], logo: "/logos/deck-clients/p42-Image264.png" },
  { slug: "vishal", name: "Vishal Mega Mart", sectors: ["Apparel & Fashion"], logo: "/logos/deck-clients/p42-Image266.png" },
  { slug: "vardhman", name: "Vardhman Textiles", sectors: ["Apparel & Fashion"], logo: "/logos/clients/vardhman.svg" },
  { slug: "arjas-steel", name: "Arjas Steel", sectors: ["Metals & Mining"], logo: "/logos/deck-clients/p42-Image270.png" },
  { slug: "rungta", name: "S R Rungta Group", sectors: ["Metals & Mining"], logo: "/logos/deck-clients/p42-Image282.png" },
  { slug: "omc", name: "Odisha Mining Corporation", sectors: ["Metals & Mining", "PSUs"], logo: "/logos/deck-clients/p42-Image274.png" },
  { slug: "welspun-corp", name: "Welspun Corp", sectors: ["Metals & Mining"], logo: "/logos/clients/welspun-corp.svg" },
  { slug: "jindal-steel-power", name: "Jindal Steel and Power", sectors: ["Metals & Mining"], logo: "/logos/clients/jindal-steel-power.svg" },
  { slug: "nalco", name: "National Aluminium Company (NALCO)", sectors: ["Metals & Mining", "PSUs"], logo: "/logos/clients/nalco.svg" },
  { slug: "vedanta", name: "Vedanta Limited", sectors: ["Metals & Mining"], logo: "/logos/clients/vedanta.svg" },
  { slug: "jsw", name: "JSW Group", sectors: ["Metals & Mining"], logo: "/logos/clients/jsw.svg" },
  { slug: "ola", name: "Ola Cabs", sectors: ["IT & Professional Services"], logo: "/logos/clients/ola.svg" },
  { slug: "tredence", name: "Tredence", sectors: ["IT & Professional Services"], logo: "/logos/clients/tredence.svg" },
  { slug: "sharechat", name: "ShareChat", sectors: ["IT & Professional Services"], logo: "/logos/clients/sharechat.jpg" },
  { slug: "avaso", name: "AVASO Technology", sectors: ["IT & Professional Services"], logo: "/logos/deck-clients/p42-Image288.png" },
  { slug: "wissen", name: "Wissen Technology", sectors: ["IT & Professional Services"], logo: "/logos/deck-clients/p42-Image292.png" },
  { slug: "altivate", name: "altivate", sectors: ["IT & Professional Services"], logo: "/logos/deck-clients/p42-Image294.png" },
  { slug: "innovaccer", name: "Innovaccer", sectors: ["IT & Professional Services"], logo: "/logos/clients/innovaccer.png" },
  { slug: "responsive", name: "Responsive (RFPIO)", sectors: ["IT & Professional Services"], logo: "/logos/deck-clients/p42-Image300.png" },
  { slug: "evoke", name: "Evoke Technologies", sectors: ["IT & Professional Services"], logo: "/logos/deck-clients/p42-Image302.png" },
  { slug: "accionlabs", name: "Accion Labs", sectors: ["IT & Professional Services"], logo: "/logos/deck-clients/p42-Image304.png" },
  { slug: "redington", name: "Redington", sectors: ["IT & Professional Services"], logo: "/logos/deck-clients/p42-Image306.png" },
  { slug: "microland", name: "Microland", sectors: ["IT & Professional Services"], logo: "/logos/clients/microland.png" },
  { slug: "welspun-one", name: "Welspun One Logistics Parks", sectors: ["Infra & Housing"], logo: "/logos/clients/welspun-one.png" },
  { slug: "wipro-infra", name: "Wipro Infrastructure Engineering", sectors: ["Infra & Housing"], logo: "/logos/deck-clients/wipro-infra.png" },
  { slug: "wework", name: "WeWork", sectors: ["Infra & Housing", "Real Estate"], logo: "/logos/clients/wework.png" },
  { slug: "afcons", name: "Afcons Infrastructure", sectors: ["Infra & Housing"], logo: "/logos/clients/afcons.svg" },
  { slug: "grohe", name: "Grohe", sectors: ["Infra & Housing"], logo: "/logos/clients/grohe.svg" },
  { slug: "kolte-patil", name: "Kolte-Patil Developers", sectors: ["Infra & Housing", "Real Estate"], logo: "/logos/deck-clients/p42-Image323.png" },
  { slug: "brickwork-india", name: "Brickwork India", sectors: ["Infra & Housing", "Services & BFSI"], logo: "/logos/deck-clients/p42-Image319.png" },
  { slug: "hero", name: "Hero MotoCorp", sectors: ["Automotives"], logo: "/logos/clients/hero.svg" },
  { slug: "triveni-turbines", name: "Triveni Turbines", sectors: ["Automotives"], logo: "/logos/deck-clients/p43-Image335.png" },
  { slug: "tata-bluescope", name: "Tata BlueScope Steel", sectors: ["Automotives"], logo: "/logos/clients/tata-bluescope.png" },
  { slug: "denso", name: "Denso", sectors: ["Automotives"], logo: "/logos/clients/denso.svg" },
  { slug: "shyam-steel", name: "Shyam Steel", sectors: ["Automotives"], logo: "/logos/clients/shyam-steel.jpg" },
  { slug: "mg-motor", name: "MG Motor India", sectors: ["Automotives"], logo: "/logos/clients/mg-motor.svg" },
  { slug: "trident-group", name: "Trident Group", sectors: ["Automotives"], logo: "/logos/clients/trident-group.jpg" },
  { slug: "arai", name: "Automotive Research Association of India (ARAI)", sectors: ["Automotives"], logo: "/logos/clients/arai.jpg" },
  { slug: "kirloskar-electric", name: "Kirloskar Electric", sectors: ["Automotives"], logo: "/logos/clients/kirloskar-electric.png" },
  { slug: "pcbl", name: "PCBL (Phillips Carbon Black)", sectors: ["Automotives"], logo: "/logos/deck-clients/p43-Image355.png" },
  { slug: "wipro", name: "Wipro", sectors: ["Automotives"], logo: "/logos/clients/wipro.svg" },
  { slug: "valvoline", name: "Valvoline", sectors: ["Chemicals"], logo: "/logos/clients/valvoline.svg" },
  { slug: "deepak-fertilisers", name: "Deepak Fertilisers and Petrochemicals", sectors: ["Chemicals"], logo: "/logos/deck-clients/p43-Image359.png" },
  { slug: "gharda", name: "Gharda Chemicals", sectors: ["Chemicals"], logo: "/logos/deck-clients/p43-Image361.png" },
  { slug: "gulbrandsen", name: "Gulbrandsen Technologies", sectors: ["Chemicals"], logo: "/logos/deck-clients/p43-Image363.png" },
  { slug: "mcpi", name: "MCPI Private Limited", sectors: ["Chemicals"], logo: "/logos/clients/mcpi.jpg" },
  { slug: "kenya-railways", name: "Kenya Railways", sectors: ["PSUs"], logo: "/logos/clients/kenya-railways.svg" },
  { slug: "ap-transco", name: "Transmission Corporation of Andhra Pradesh (APTRANSCO)", sectors: ["PSUs"], logo: "/logos/deck-clients/p43-Image371.png" },
  { slug: "delhi-transco", name: "Delhi Transco Limited", sectors: ["PSUs"], logo: "/logos/deck-clients/p43-Image374.png" },
  { slug: "ntpc", name: "NTPC", sectors: ["PSUs"], logo: "/logos/clients/ntpc.svg" },
  { slug: "bsnl", name: "BSNL", sectors: ["PSUs"], logo: "/logos/clients/bsnl.svg" },
  { slug: "bhel", name: "BHEL", sectors: ["PSUs"], logo: "/logos/clients/bhel.svg" },
  { slug: "ncdex", name: "NCDEX", sectors: ["Services & BFSI"], logo: "/logos/clients/ncdex.png" },
  { slug: "narayan-seva", name: "Narayan Seva Sansthan", sectors: ["Services & BFSI"], logo: "/logos/clients/narayan-seva.png" },
  { slug: "groww", name: "Groww", sectors: ["Services & BFSI"], logo: "/logos/clients/groww.png" },
  { slug: "niit", name: "NIIT", sectors: ["Services & BFSI"], logo: "/logos/clients/niit.svg" },
  { slug: "pos-malaysia", name: "Pos Malaysia", sectors: ["Services & BFSI"], logo: "/logos/clients/pos-malaysia.svg" },
  { slug: "trilegal", name: "Trilegal", sectors: ["Services & BFSI"], logo: "/logos/clients/trilegal.png" },
  { slug: "cyril-amarchand", name: "Cyril Amarchand Mangaldas", sectors: ["Services & BFSI"], logo: "/logos/clients/cyril-amarchand.svg" },
  { slug: "aipl", name: "Advance India Projects (AIPL)", sectors: ["Real Estate"], logo: "/logos/deck-clients/p43-Image404.png" },
  { slug: "pavai", name: "Pavai", sectors: ["Real Estate"], logo: "/logos/deck-clients/p43-Image410.png" },
  { slug: "anarock", name: "Anarock", sectors: ["Real Estate"], logo: "/logos/deck-clients/p43-Image406.png" },
  { slug: "varindera", name: "Varindera Constructions", sectors: ["Real Estate"], logo: "/logos/deck-clients/p43-Image408.png" },
  { slug: "panchshil", name: "Panchshil Realty", sectors: ["Real Estate"], logo: "/logos/deck-clients/p43-Image412.png" },
  { slug: "orient-cement", name: "Orient Cement", sectors: ["Others"], logo: "/logos/deck-clients/p43-Image327.png" },
  { slug: "physics-wallah", name: "Physics Wallah", sectors: ["Others"], logo: "/logos/clients/physics-wallah.svg" },
  { slug: "jk-paper", name: "JK Paper", sectors: ["Others"], logo: "/logos/deck-clients/p43-Image329.png" },
  { slug: "bajaj-allianz", name: "Bajaj Allianz", sectors: ["Others"], logo: "/logos/clients/bajaj-allianz.svg" },
  { slug: "inlife", name: "InLife / Insular Life", sectors: ["Others"], logo: "/logos/clients/inlife.png" },
  { slug: "diyar", name: "Diyar Middle East", sectors: ["IT & Professional Services"], logo: "/logos/deck-clients/p42-Image296.png" },
  { slug: "itb-group", name: "ITB Group", sectors: ["Automotives"], logo: "/logos/deck-clients/p43-Image352.png" },
  { slug: "niamt", name: "NIAMT Ranchi", sectors: ["PSUs"], logo: "/logos/deck-clients/p43-Image382.png" },
];
