// Generated by scripts/fetch-youtube.mjs from the channel's public feed; do not edit by hand.
// Newest first. Thumbnails are saved under public/youtube/<id>.jpg by the same script.
export const YOUTUBE_CHANNEL_URL = "https://www.youtube.com/channel/UCdUFIRwrZMoq4oUvPt3KuPQ";
export type YoutubeVideo = { id: string; title: string; published: string };
export const youtubeVideos: YoutubeVideo[] = [
  {
    id: "ZlSzZ_Qz694",
    title: "Testimonial Video- Mr. Hari Narayan – CGM HR, Power Grid Corporation of India Limited",
    published: "2025-12-05",
  },
  {
    id: "g0PBxc5hZnc",
    title: "Customer Testimony-Dr. Yatindra Dwivedi, Director Personnel- Power Grid Corporation of India Limited",
    published: "2025-11-20",
  },
  { id: "YN2y9STqw9A", title: "Neeraj Pandey, Vice President-IBG", published: "2025-06-18" },
  { id: "IB5OUrVxh0c", title: "SAP SuccessFactors Go-Live – A Major Milestone Achieved!🚀", published: "2025-06-11" },
  { id: "9AqSY6LITYc", title: "Go-live Celebrations at IB Group", published: "2025-05-14" },
  {
    id: "nkPYsriLWf8",
    title: "Unleashing the Power of Business AI | SAP NOW AI Tour Mumbai 2025",
    published: "2025-04-25",
  },
  { id: "X0T1l1lKYQM", title: "RISE with SAP S/4HANA Go-Live Celebration at TGNPDCL", published: "2025-04-25" },
  { id: "0K-PUVPpXtw", title: "Empowering Businesses with SAP Excellence!", published: "2025-04-07" },
  {
    id: "84bYKW7x7ec",
    title: "In2IT EBS at SAP Partner Kick-Off 2025-Dubai | Driving Innovation & Growth",
    published: "2025-02-28",
  },
  { id: "OBaVLfvFVX4", title: "SAP SuccessFactors Go-live Celebrations at Rungta Mines Ltd", published: "2025-02-25" },
  { id: "agIJkC-WY-w", title: "SAP Go to Market Kick OffV5", published: "2025-01-27" },
  { id: "bUIrAGjPWSc", title: "Beyond Work: A Year of Joy & Togetherness!", published: "2025-01-17" },
  { id: "HYgBhdbMzLU", title: "Elevate Your HR Career with IN2IT EBS!", published: "2024-10-22" },
  { id: "hMEcDg4pr1M", title: "SAP SuccessFactors Go-Live Celebration at Innovaccer", published: "2024-10-08" },
  { id: "3EJqv949acU", title: "Transforming HR with SAP PMGM & In2IT EBS!", published: "2024-08-28" },
];
